//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 10:33:12 AM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://service.ws.respuesta.aereos.privados.www.ventanillaunica.gob.mx/")
package myproject.wsdl.currency;
